import { ESCALATION_PHASE_LABELS } from './types'
import type { PersonalisationRecord, StrategyTemplate } from './types'

// Print-friendly HTML, not a bundled PDF library — the practitioner uses
// the browser's native print-to-PDF, matching the FBA tool's
// DocumentationExport pattern (brief §6/§8: "assembles, doesn't generate").

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function fmtDateTime(iso: string): string {
  return new Date(iso).toLocaleString()
}

export interface PlanReadyEntry {
  personalisation: PersonalisationRecord
  strategy: StrategyTemplate
}

export function renderPlanReadyExport(entries: PlanReadyEntry[], generatedBy: string, generatedAt: string): string {
  const sections = entries
    .map(({ personalisation, strategy }) => {
      // §5 hard UI rule carries into export: a superseded strategy's
      // evidence must never be quoted without that context.
      const supersededNote = strategy.supersededBy
        ? `<p class="caveat">This strategy's evidence base has been superseded by a later study — see the full record in the library before relying on the figure below.</p>`
        : ''
      return `
    <section class="entry">
      <h2>${escapeHtml(strategy.technique_name)}</h2>
      <p class="meta">Participant: ${escapeHtml(personalisation.participantIdentifyingDetails)}</p>
      <table class="kv">
        <tr><th>Category</th><td>${escapeHtml(strategy.strategy_category.join(', ') || (strategy.is_responsive ? 'Responsive' : '—'))}</td></tr>
        ${
          personalisation.escalationPhase
            ? `<tr><th>Escalation phase</th><td>${escapeHtml(ESCALATION_PHASE_LABELS[personalisation.escalationPhase])}</td></tr>`
            : ''
        }
        <tr><th>Personalised activity</th><td>${escapeHtml(personalisation.personalisedActivity)}</td></tr>
        <tr><th>Rationale</th><td>${escapeHtml(personalisation.rationale)}</td></tr>
        <tr><th>Evidence summary</th><td>${escapeHtml(strategy.evidence_summary)}</td></tr>
        ${
          strategy.capacity_considerations.length
            ? `<tr><th>Capacity considerations</th><td>${escapeHtml(strategy.capacity_considerations.join(', '))} — ${escapeHtml(strategy.capacity_considerations_note)}</td></tr>`
            : ''
        }
        <tr><th>Recorded by</th><td>${escapeHtml(personalisation.createdBy)} on ${escapeHtml(fmtDateTime(personalisation.createdAt))}</td></tr>
      </table>
      ${supersededNote}
    </section>`
    })
    .join('')

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Personalised Strategy Plan Entries</title>
<style>
  body { font-family: system-ui, sans-serif; color: #0f172a; max-width: 840px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  h1 { font-size: 1.5rem; }
  h2 { font-size: 1.2rem; margin-top: 2rem; border-bottom: 1px solid #cbd5e1; padding-bottom: 0.25rem; }
  table.kv { border-collapse: collapse; width: 100%; margin: 0.5rem 0; font-size: 0.9rem; }
  table.kv th, table.kv td { border: 1px solid #cbd5e1; padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; }
  table.kv th { background: #f1f5f9; width: 200px; }
  .caveat { font-size: 0.85rem; color: #92400e; background: #fffbeb; border: 1px solid #fde68a; padding: 0.5rem; border-radius: 4px; }
  .meta { font-size: 0.85rem; color: #64748b; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
  <h1>Personalised Strategy Plan Entries</h1>
  <p class="meta">
    Generated by ${escapeHtml(generatedBy)} on ${escapeHtml(fmtDateTime(generatedAt))}<br />
    Assembled from the Strategy Library and the practitioner's own personalisation and rationale. This is decision
    support, not a generated plan — every selection and every word of rationale above was authored by the
    practitioner, not produced by this tool.
  </p>
  ${sections}
</body>
</html>`
}
